apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: dev
spec:
  encryptedData:
    password: AgDPexJT5fSFE4gu2R13R29TG5QVrImcJQ27n9fxtbQOI/QWMLHsxsOBWQOPI4Ooom6gWoP2YKYx3N4CnDH9+wohblwWe0x6sZIuoZmQ8EdJg8xGOW4jEL9+4qQxjjLk5g7rJcgpZmp0Q7WvHv+Z46fTXr+wChC8rVc8rboEsKW6r0YH+bIW1LMPIL9K8tbVlg7Em54OY+JYhboiWyaxc8PpcM88AJ45nsw3iyCx8s78sqp6r2LqKkJDUD+l6TS92leYEOyXykyc7TSUwK7OWhO00Gy8wczKr18hmralF7v5tCCGEMN0cGryS3Yvo7+2RgTJHLeoKLO39ysZ09bMKe6kdEs43uiDeNMz3kFCiGkm2T7sHsHEzhCrdLYM2HKdYizgAl/qPHu9teIZGCcg6UUSVffE1FJrlyLk6dGDXt2Fh0bQkg0+ju/gI36glq6wV/lh5Sfb4M08xghopMwryz65ckipfOx9tZvtWFa443mI6EK7fQadmdH9kcMhoxFNNkP35qNg4cXF9UbwCtIZ+xWwwA3s8mkrbaQnL+A3VmIAL6JHH5Y8taIpy8wZPzOPWGVKKI/ctlz5Cz33Wk7CWceTP1Low2fSiyCk605OhQlw+M/qDAeHhWbezHAZfCopCjrpd/Ef1FtYXcDTk7+Hka9WjtimObo8hgd+HHqkyO3r5csuRrZbkQpuLhsm+Xx4TIazqa4nPQ==
    user: AgD1coP3CFqf2h2q6kqdoHTSYEL9VBxJzDzllWenWXikRagMgBM6DI/LIf+t/kn0H82dW3AednI/x2dRXxiYV2TPNcwGO1tqSz51grz5/piZe+yhRNlBJtS4knoniwFL8CZq2GyWyQLp2hDbgew5MRZRtppteVNGC4YeXGDT+0Du8vD7Zzl+BwerXBCY6jilyzsQ+KQ8y+PIJ7S2A9mfia2qRDRVuWf0T5MTWiqtDn7pHY2QK4hDi3d/9o96LxTahg3sSqfo0KhQVRYobi0MBtuAHOqq27lmOObhRDYUFBxg3zOYWIYpN2HLQMNj4oFIpVfuka2B1EUWiEPLSOoYub4OU2t/vC+EkyDMavlQPA634CyHXg5tX72v6ldzP0APPSM6OoO0IAqNinKaC+GVJPlFqXErerkxAaYrHt4rGmMeTAr6nGwKvX70vEu9klL1tjhsIZCJb84Xx1Ix9IuH0U0Cbod0oTusjG5HQ5V+kSfmyhTP2t06cy9l+rsjYf6Gnc8gZKGYNuul+p+b8VzOoa6inphhIDM+LoBbSn7QrNlQp8uj2eeM1VESUhJMOOTTYfgg9mclJ5UMBcKEVjmm7P1fof/ctT08l6Ip12R8tORHnA571vPOufhU4K++JJ8brxVWk6eZ1OWQooovAVvuun7fZnsf0ozAGIwYRsqbhB0+sbr9NHQ3Y0sOh8g52/IOwJd3u7ld6A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: dev

