apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: epsagon
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.3
spec:
  releaseName: epsagon
  chart:
    repository: https://helm.epsagon.com
    name: epsagon   
    version: 0.1.19 
  values:
    ingress:
      enabled: false
    image: 
      repository: epsagon/cluster-agent