apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: epsagon
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.1
spec:
  releaseName: epsagon-cluster-agent
  chart:
    repository: https://helm.epsagon.com
    name: epsagon   
    version: 0.1.19 
  values:
    ingress:
      enabled: false
    image: 
      repository: epsagon/cluster-agent