---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: epsagon-agent-2
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:~0.1
spec:
  releaseName: epsagon-cluster-agent
  chart:
    repository: https://helm.epsagon.com
    name: cluster-agent   
    version: 0.1.19 
  values:
    ingress:
      enabled: false
    image: 
      repository: epsagon/cluster-agent