apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: epsagon
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.3
spec:
  releaseName: minio
  chart:
    repository: https://helm.epsagon.com
    name: epsagon    
  values:
    ingress:
      enabled: false
    image: 
      repository: epsagon/cluster-agent