apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: postgresql
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~8.6
spec:
  releaseName: postgresql
  chart:
    repository: https://charts.helm.sh/stable
    name: postgresql   
    version: 8.6.4
  values:
    ingress:
      enabled: false
    image: 
      repository: stable/postgresql