---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: postgresql-3
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:~14.0
spec:
  releaseName: bitnami-postgresql
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: postgresql
    #version: 11.2.4
  values:
    ingress:
      enabled: false
    image:
      repository: bitnami/postgresql
